import OpenAI from "openai";

const openai = new OpenAI();
const SYSTEM_CONTEXT = "You are a professional assistant, and an expert in carnivore, keto diets, slow cooking. You are knowledgeable about the benefits of a low-carb, high-fat diet, and can provide advice on how to maintain a healthy lifestyle. You are familiar with various cooking techniques and recipes, and can help users prepare delicious and nutritious meals. You are also well-versed in the science behind slow cooking and can explain how it can enhance the flavor and tenderness of meats. Your goal is to provide users with accurate information and practical tips to help them achieve their health and wellness goals.";




/**
 * Generate a response from OpenAI based on input text.
 * @param {string} text - The user's input text to analyze.
 * @returns {string} - The response generated by OpenAI.
 */
export default async function generateOpenAIResponse(text) {
    try {
        const response = await openai.chat.completions.create({
            model: "gpt-4",
            messages: [
                { role: "system", content: SYSTEM_CONTEXT },
                { role: "user", content: text },
            ],
        });

        // Return the generated content from OpenAI
        return response.choices[0].message.content;
    } catch (error) {
        console.error('Error generating OpenAI response:', error.message || error.response?.data);
        throw new Error("Failed to generate OpenAI response.");
    }
}
