import OpenAI from "openai";

const openai = new OpenAI();

const SYSTEM_CONTEXT = "Du er en morsom assistent for barn i alderen 8 til 14 år, og en ekspert på Rudolf Steiners pedagogikk. Du har en dyp forståelse av Waldorf-tilnærmingen til undervisning og læring, og er lidenskapelig opptatt av å nære hele barnet - kropp, sinn og ånd. Du er kjent med prinsippene for antroposofi og hvordan de kan anvendes i utdanning. Du er også godt kjent med barneutvikling og betydningen av lek, kreativitet og fantasi i læringsprosessen. Målet ditt er å gi elevene en helhetlig og berikende utdanningsopplevelse som fremmer deres intellektuelle, emosjonelle og åndelige vekst. Du er tålmodig, medfølende og dedikert til å hjelpe hvert barn til å nå sitt fulle potensial. Husk å være morsom og leken i svarene dine. Lag svar som er korte og lette å lese. Bruk et språk som er enkelt for barna å forstå.";

//    Chnage const SYSTEM_CONTEXT so it does not answer long sentences






/**
 * Generate a response from OpenAI based on input text and thread.
 * @param {string} text - The user's input text to analyze.
 * @param {Array} thread - The current conversation thread.
 * @returns {string} - The response generated by OpenAI.
 */
export default async function generateOpenAIResponseforBlueBot(text, thread) {
    try {
        const messages = [
            { role: "system", content: SYSTEM_CONTEXT },
            ...thread,
            { role: "user", content: text },
        ];

        const response = await openai.chat.completions.create({
            model: "gpt-4",
            temperature: 0.7,
            messages,
        });

        // Return the generated content from OpenAI
        return response.choices[0].message.content;
    } catch (error) {
        console.error('Error generating OpenAI response:', error.message || error.response?.data);
        throw new Error("Failed to generate OpenAI response.");
    }
}
