import OpenAI from "openai";
const openai = new OpenAI();
/**
 * Generate a response from OpenAI based on input text.
 * @param {string} text - The user's input text to analyze.
 * @returns {string} - The response generated by OpenAI.
 */
export default async function generateOpenAIResponse(text) {
    try {
        const response = await openai.chat.completions.create({
            model: "gpt-4",
            messages: [
                { role: "system", content: "You are a professional assistant. Respond in markdown with appropriate titles." },
                { role: "user", content: text },
            ],
        });
        // Return the generated content from OpenAI
        return response.choices[0].message.content;
    } catch (error) {
        console.error('Error generating OpenAI response:', error.message || error.response?.data);
        throw new Error("Failed to generate OpenAI response.");
    }
}